language: node_js
node_js:
- '0.12'
- '0.10'
install:
- npm install
- npm install -g grunt-cli
script: grunt travis
deploy:
  provider: npm
  email: krzysiek@codilogy.com
  api_key:
     secure: KJqi/YE8aTH+ZcH9g6awDD4ZmyciVtdWahwUTmc2CH2KySHvR+SR/WCNDyjxqn6iVCWuDrJNr6OA91PI4+HxL6RXoLe7Z3IhtoD9QlVxbenhK0ZmN7Q/NXN4w3+yTlgO7RCg9DsIpo6u3M6wLXNyBRBUIuWAnYU1gJuJ8DMiS/4=
  on:
    node: 0.12
    tags: true
    repo: kwiniarski/spiral-cerber
